version: '1.0'
services:

  #Launches ollama, with custom build file
  ollama:
    image: ollama/ollama:rocm
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama_data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    build:
      context: .
      dockerfile: ./ollama_docker/ollama.dockerfile    
    # networks:
    #   - ollama-docker
